use_frameworks!

platform :ios, '16.0'

target 'SDKWrapperLibrary_Example' do
  pod 'SDKWrapperLibrary', :path => '../'

  target 'SDKWrapperLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
